-- Crear la tabla de Cajas
create table public.cajas (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null default auth.uid(),
  monto_inicial numeric(12, 4) not null default 0,
  reposicion numeric(12, 4) not null default 0,
  numero_cheque_reposicion text,
  fecha_apertura timestamp with time zone not null default now(), -- Fecha creación manual
  fecha_cierre timestamp with time zone, -- Nulo hasta que se cierre
  responsable text not null,
  sucursal text not null, -- Guardado como texto del select
  estado text not null default 'abierta', -- abierta / cerrada
  banco_reposicion text -- Banco del cheque de reposición
);

-- Habilitar Row Level Security (RLS)
alter table public.cajas enable row level security;

-- Política de seguridad: Los usuarios solo pueden ver y editar sus propias cajas
create policy "Usuarios pueden gestionar sus propias cajas"
  on public.cajas for all
  using (auth.uid() = user_id);
