create type tipo_notificacion as enum ('info', 'warning', 'error', 'success');

create table notificaciones (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id), -- Null means global/admin notification
    titulo text not null,
    mensaje text not null,
    tipo tipo_notificacion default 'info',
    leido boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table notificaciones enable row level security;

-- Users can read their own notifications or global ones (user_id is null)
create policy "Usuarios pueden ver sus notificaciones"
    on notificaciones for select
    using (auth.uid() = user_id or user_id is null);

-- System can insert notifications (and admins if needed)
create policy "Sistema puede crear notificaciones"
    on notificaciones for insert
    with check (true);

-- Users can update "leido" status of their own notifications
create policy "Usuarios pueden actualizar sus notificaciones"
    on notificaciones for update
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

-- Enable Realtime
alter publication supabase_realtime add table notificaciones;
