create type tipo_notificacion as enum ('info', 'warning', 'error', 'success');

create table notificaciones (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id), -- Null means global/admin notification
    empresa_id uuid references empresas(id), -- Null means global/system notification
    titulo text not null,
    mensaje text not null,
    tipo tipo_notificacion default 'info',
    leido boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table notificaciones enable row level security;

-- Users can read their own notifications or those for their company
create policy "Usuarios pueden ver sus notificaciones"
    on notificaciones for select
    using (
        auth.uid() = user_id 
        or (empresa_id in (select empresa_id from empresa_usuarios where user_id = auth.uid()))
        or (user_id is null and empresa_id is null) -- Global system notifications
    );

-- System can insert notifications
create policy "Sistema puede crear notificaciones"
    on notificaciones for insert
    with check (true);

-- Users can update "leido" status of their own or company notifications
create policy "Usuarios pueden actualizar sus notificaciones"
    on notificaciones for update
    using (
        auth.uid() = user_id
        or (empresa_id in (select empresa_id from empresa_usuarios where user_id = auth.uid()))
    )
    with check (
        auth.uid() = user_id
        or (empresa_id in (select empresa_id from empresa_usuarios where user_id = auth.uid()))
    );

-- Enable Realtime
alter publication supabase_realtime add table notificaciones;
