-- Crear la tabla de Proveedores
create table public.proveedores (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null default auth.uid(),
  ruc text not null,
  nombre text not null, -- Razón Social o Nombre
  actividad_economica text,
  regimen text
);

-- Habilitar Row Level Security (RLS) para seguridad
alter table public.proveedores enable row level security;

-- Política de seguridad: Los usuarios solo pueden ver y editar sus propios proveedores
create policy "Usuarios pueden gestionar sus propios proveedores"
  on public.proveedores for all
  using (auth.uid() = user_id);
