-- Crear la tabla de Regímenes Tributarios
create table if not exists public.regimenes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null default auth.uid(),
  nombre text not null,
  descripcion text
);

-- Habilitar RLS
alter table public.regimenes enable row level security;

create policy "Usuarios pueden gestionar sus propios regimenes"
  on public.regimenes for all
  using (auth.uid() = user_id);
