-- Tabla principal de Retenciones
create table public.retenciones (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null default auth.uid(),
  transaccion_id bigint references public.transacciones(id) on delete cascade not null,
  fecha_retencion date not null,
  numero_retencion text not null,
  total_fuente numeric(12, 4) not null default 0,
  total_iva numeric(12, 4) not null default 0,
  total_retenido numeric(12, 4) not null default 0,
  unique(transaccion_id) -- Solo una retención por transacción
);

-- Detalle de Retenciones (por ítem de la factura original)
create table public.retencion_items (
  id bigint generated by default as identity primary key,
  retencion_id bigint references public.retenciones(id) on delete cascade not null,
  transaccion_item_id bigint references public.transaccion_items(id) not null,
  tipo text not null check (tipo in ('bien', 'servicio')),
  base_imponible numeric(12, 4) not null,
  porcentaje_fuente numeric(5, 2) not null default 0, -- Ej: 1.75, 2.00, etc.
  monto_fuente numeric(12, 4) not null default 0,
  porcentaje_iva numeric(5, 2) not null default 0, -- Ej: 30, 70, 100
  monto_iva numeric(12, 4) not null default 0
);

-- RLS para Retenciones
alter table public.retenciones enable row level security;
create policy "Usuarios gestionan sus propias retenciones"
  on public.retenciones for all
  using (auth.uid() = user_id);

-- RLS para Ítems de Retención
alter table public.retencion_items enable row level security;
create policy "Usuarios gestionan items de sus retenciones"
  on public.retencion_items for all
  using (
    exists (
      select 1 from retenciones 
      where retenciones.id = retencion_items.retencion_id 
      and retenciones.user_id = auth.uid()
    )
  );
