-- Crear la tabla de Sucursales
create table if not exists public.sucursales (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null default auth.uid(),
  nombre text not null,
  direccion text
);

-- Habilitar RLS
alter table public.sucursales enable row level security;

create policy "Usuarios pueden gestionar sus propias sucursales"
  on public.sucursales for all
  using (auth.uid() = user_id);

-- Crear la tabla de Bancos
create table if not exists public.bancos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null default auth.uid(),
  nombre text not null
);

-- Habilitar RLS
alter table public.bancos enable row level security;

create policy "Usuarios pueden gestionar sus propios bancos"
  on public.bancos for all
  using (auth.uid() = user_id);
