-- Tabla principal de Transacciones
create table public.transacciones (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null default auth.uid(),
  caja_id bigint references public.cajas(id) on delete cascade not null,
  proveedor_id bigint references public.proveedores(id) not null,
  fecha_factura date not null default current_date,
  numero_factura text not null,
  total_factura numeric(12, 4) not null default 0
);

-- Tabla de Ítems (Productos) de la factura
create table public.transaccion_items (
  id bigint generated by default as identity primary key,
  transaccion_id bigint references public.transacciones(id) on delete cascade not null,
  nombre text not null,
  monto numeric(12, 4) not null,
  con_iva boolean not null default false, -- true = 15%, false = 0%
  monto_iva numeric(12, 4) not null default 0,
  subtotal numeric(12, 4) not null default 0
);

-- RLS para Transacciones
alter table public.transacciones enable row level security;
create policy "Usuarios gestionan sus propias transacciones"
  on public.transacciones for all
  using (auth.uid() = user_id);

-- RLS para Ítems (Heredado por la relación)
-- Nota: Supabase permite usar un join o check en la política de items
alter table public.transaccion_items enable row level security;
create policy "Usuarios gestionan items de sus transacciones"
  on public.transaccion_items for all
  using (
    exists (
      select 1 from transacciones 
      where transacciones.id = transaccion_items.transaccion_id 
      and transacciones.user_id = auth.uid()
    )
  );
