-- Create notifications table
create type tipo_notificacion as enum ('info', 'warning', 'error', 'success');

create table notificaciones (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id), -- Null means global/admin notification
    titulo text not null,
    mensaje text not null,
    tipo tipo_notificacion default 'info',
    leido boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table notificaciones enable row level security;

-- Users can read their own notifications or global ones (user_id is null)
create policy "Usuarios pueden ver sus notificaciones"
    on notificaciones for select
    using (auth.uid() = user_id or user_id is null);

-- System can insert notifications (and admins if needed)
create policy "Sistema puede crear notificaciones"
    on notificaciones for insert
    with check (true);

-- Users can update "leido" status of their own notifications
create policy "Usuarios pueden actualizar sus notificaciones"
    on notificaciones for update
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

-- Enable Realtime
alter publication supabase_realtime add table notificaciones;

-- Trigger function to check low balance
create or replace function check_low_balance()
returns trigger as $$
declare
    v_caja_id bigint;
    v_monto_inicial numeric;
    v_total_ingresos numeric;
    v_total_egresos numeric;
    v_saldo_actual numeric;
    v_porcentaje_alerta integer;
    v_limite_alerta numeric;
begin
    -- Only check on INSERT (assuming all transactions are expenses/gastos for now based on schema)
    -- If there's no 'tipo' column, we assume everything in this table is a decrease in balance?
    -- Actually, if we look at the view (pending check), we'll know.
    -- For now, removing the check NEW.tipo = 'gasto' as column doesn't exist.
    
    v_caja_id := NEW.caja_id;

    -- Get caja info
    select monto_inicial into v_monto_inicial from cajas where id = v_caja_id;

    -- Get configuration percentage (default to 15 if not set)
    select coalesce(valor::integer, 15) into v_porcentaje_alerta 
    from configuracion where clave = 'porcentaje_alerta_caja';

    -- Calculate current balance
    -- Assuming 'transacciones' are ALL expenses. 
    -- If there are other tables for income, we need to sum them as well?
    -- Let's assume for this fix that we just sum total_factura from transacciones as expenses.
    
    -- NOTE: Ideally we should query the view `v_cajas_con_saldo` but PL/PGSQL triggers with views can be tricky depending on permissions/scope.
    -- Let's simplify: Balance = Initial - Sum(Transactions)
    
    select coalesce(sum(total_factura), 0) into v_total_egresos 
    from transacciones where caja_id = v_caja_id;

    v_saldo_actual := v_monto_inicial - v_total_egresos;
    v_limite_alerta := v_monto_inicial * (v_porcentaje_alerta::numeric / 100);

    -- If balance is below limit, trigger notification
    if v_saldo_actual < v_limite_alerta then
        insert into notificaciones (titulo, mensaje, tipo)
        values (
            'Saldo Bajo en Caja #' || v_caja_id,
            'El saldo actual (' || v_saldo_actual || ') es inferior al ' || v_porcentaje_alerta || '% del monto inicial.',
            'warning'
        );
    end if;

    return NEW;
end;
$$ language plpgsql;

create trigger trigger_check_low_balance
after insert on transacciones
for each row execute function check_low_balance();

-- Trigger function to check large movements
create or replace function check_large_movement()
returns trigger as $$
begin
    -- Threshold hardcoded to 1000 for now, can be moved to config later
    if NEW.total_factura > 1000 then
        insert into notificaciones (titulo, mensaje, tipo)
        values (
            'Movimiento Grande Registrado',
            'Se ha registrado una transacción de ' || NEW.total_factura || ' en la Caja #' || NEW.caja_id,
            'info'
        );
    end if;
    return NEW;
end;
$$ language plpgsql;

create trigger trigger_check_large_movement
after insert on transacciones
for each row execute function check_large_movement();
