-- Create bitacora table for audit logs
create table public.bitacora (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users(id),
  accion text not null, -- e.g., 'ELIMINAR_CAJA', 'CIERRE_CAJA'
  detalle jsonb, -- Flexible field for storing IDs, snapshots, etc.
  ip_address text -- Optional, for future use
);

-- RLS Policies
alter table public.bitacora enable row level security;

-- Authenticated users can insert logs (system actions triggered by user)
create policy "Usuarios pueden crear registros de bitacora"
  on public.bitacora for insert
  with check (auth.uid() = user_id);

-- Only admins or specific roles should view (for now, allow auth users to view for the settings page)
create policy "Usuarios pueden ver bitacora"
  on public.bitacora for select
  using (auth.uid() IS NOT NULL);
