-- =============================================================================
-- Migración 014: Sistema de Empresas (Comercios)
-- Crea las tablas empresas y empresa_usuarios para multi-tenancy
-- =============================================================================

-- 1. Tabla de Empresas (Comercios)
CREATE TABLE public.empresas (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  nombre TEXT NOT NULL,
  ruc TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  created_by UUID REFERENCES auth.users(id) NOT NULL
);

ALTER TABLE public.empresas ENABLE ROW LEVEL SECURITY;

-- 2. Tabla de relación: usuarios pertenecen a una empresa
CREATE TABLE public.empresa_usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id UUID REFERENCES public.empresas(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  role TEXT NOT NULL DEFAULT 'operador' CHECK (role IN ('owner', 'admin', 'operador')),
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  UNIQUE(empresa_id, user_id)
);

ALTER TABLE public.empresa_usuarios ENABLE ROW LEVEL SECURITY;

-- 3. Función helper: obtener la empresa_id del usuario autenticado
--    Usada como DEFAULT en columnas y en políticas RLS
CREATE OR REPLACE FUNCTION public.get_user_empresa_id()
RETURNS UUID AS $$
  SELECT empresa_id FROM public.empresa_usuarios
  WHERE user_id = auth.uid()
  LIMIT 1;
$$ LANGUAGE SQL SECURITY DEFINER STABLE;

-- 4. Políticas RLS para empresas
CREATE POLICY "Usuarios ven su empresa"
  ON public.empresas FOR SELECT
  USING (id = public.get_user_empresa_id());

CREATE POLICY "Usuarios crean empresa"
  ON public.empresas FOR INSERT
  WITH CHECK (created_by = auth.uid());

CREATE POLICY "Usuarios actualizan su empresa"
  ON public.empresas FOR UPDATE
  USING (id = public.get_user_empresa_id());

-- 5. Políticas RLS para empresa_usuarios
CREATE POLICY "Usuarios ven miembros de su empresa"
  ON public.empresa_usuarios FOR SELECT
  USING (empresa_id = public.get_user_empresa_id());

-- Solo usuarios de la empresa pueden agregar miembros
CREATE POLICY "Usuarios agregan miembros a su empresa"
  ON public.empresa_usuarios FOR INSERT
  WITH CHECK (empresa_id = public.get_user_empresa_id() OR NOT EXISTS (
    SELECT 1 FROM public.empresa_usuarios WHERE user_id = auth.uid()
  ));

CREATE POLICY "Usuarios eliminan miembros de su empresa"
  ON public.empresa_usuarios FOR DELETE
  USING (empresa_id = public.get_user_empresa_id());
