-- =============================================================================
-- Migración 017: Sistema de Invitaciones
-- Permite a owners/admins invitar usuarios por email a su empresa
-- =============================================================================

CREATE TABLE public.invitaciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id UUID REFERENCES public.empresas(id) ON DELETE CASCADE NOT NULL,
  email TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'operador' CHECK (role IN ('admin', 'operador')),
  status TEXT NOT NULL DEFAULT 'pendiente' CHECK (status IN ('pendiente', 'aceptada', 'rechazada')),
  invited_by UUID REFERENCES auth.users(id) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  accepted_at TIMESTAMPTZ,
  UNIQUE(empresa_id, email)
);

ALTER TABLE public.invitaciones ENABLE ROW LEVEL SECURITY;

-- Miembros de la empresa pueden ver las invitaciones de su empresa
CREATE POLICY "Empresa ve sus invitaciones"
  ON public.invitaciones FOR SELECT
  USING (empresa_id = public.get_user_empresa_id());

-- Owner/admin pueden crear invitaciones
CREATE POLICY "Empresa crea invitaciones"
  ON public.invitaciones FOR INSERT
  WITH CHECK (empresa_id = public.get_user_empresa_id());

-- Owner/admin pueden actualizar invitaciones
CREATE POLICY "Empresa actualiza invitaciones"
  ON public.invitaciones FOR UPDATE
  USING (empresa_id = public.get_user_empresa_id());

-- Owner/admin pueden eliminar invitaciones
CREATE POLICY "Empresa elimina invitaciones"
  ON public.invitaciones FOR DELETE
  USING (empresa_id = public.get_user_empresa_id());

-- Política especial: usuarios sin empresa pueden ver invitaciones con su email
-- Esto permite que un usuario nuevo vea si tiene invitación pendiente
CREATE POLICY "Usuarios ven sus propias invitaciones"
  ON public.invitaciones FOR SELECT
  USING (email = (SELECT email FROM auth.users WHERE id = auth.uid()));

-- Política: usuarios sin empresa pueden aceptar su propia invitación
CREATE POLICY "Usuarios aceptan su invitacion"
  ON public.invitaciones FOR UPDATE
  USING (email = (SELECT email FROM auth.users WHERE id = auth.uid()))
  WITH CHECK (email = (SELECT email FROM auth.users WHERE id = auth.uid()));

CREATE INDEX idx_invitaciones_email ON public.invitaciones(email);
CREATE INDEX idx_invitaciones_empresa ON public.invitaciones(empresa_id);
