-- Tabla de Productos Recurrentes
-- Permite a las empresas registrar productos de compra frecuente
-- para agilizar el registro de transacciones.

CREATE TABLE public.productos_recurrentes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id UUID REFERENCES public.empresas(id) ON DELETE CASCADE NOT NULL,
    nombre TEXT NOT NULL,
    valor_unitario NUMERIC(12, 4) NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- RLS
ALTER TABLE public.productos_recurrentes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Usuarios gestionan productos de su empresa"
    ON public.productos_recurrentes FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.empresa_usuarios
            WHERE empresa_usuarios.empresa_id = productos_recurrentes.empresa_id
            AND empresa_usuarios.user_id = auth.uid()
        )
    );

-- Índice para búsqueda rápida por empresa
CREATE INDEX idx_productos_recurrentes_empresa ON public.productos_recurrentes(empresa_id);
